(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Title: CoxeterGeneratingSets *) 
(* :Author: David Sheard *)
(* :Summary: Functions to compute and manipulate generating sets of Coxeter groups. *)
(* :Context: CoxeterGroups`CoxeterGeneratingSets` *)
(* :Package version: 1.0 *)
(* :History:  Version 1.0 February 28 2022 *)
(* :Mathematica version: 12.0.0 for Microsoft Windows (64-bit) (April 6, 2019) *)
(* :Discussion: Give more details here.*)


BeginPackage["CoxeterGroups`CoxeterGeneratingSets`"];


Unprotect[

];
ClearAll[

];


Begin["`Private`"];


Unprotect[

];
ClearAll[

];


Protect[

];


End[];


Protect[

];


EndPackage[];
