(* Created with the Wolfram Language : www.wolfram.com *)
Paclet[Name -> "CoxeterGroups", Version -> "0.0.1", 
 MathematicaVersion -> "8+", Extensions -> 
  {{"Kernel", "Context" -> {"CoxeterGroups`BasicCoxeterFunctions`", 
      "CoxeterGroups`CoxeterCombinatorics`", 
      "CoxeterGroups`CoxeterGeneratingSets`", 
      "CoxeterGroups`CoxeterVisualisation`", 
      "CoxeterGroups`ElementEnumeration`", "CoxeterGroups`FoldingComplexes`", 
      "CoxeterGroups`FreeGroups`", "CoxeterGroups`FundamentalGroups`", 
      "CoxeterGroups`PoincarePolynomials`", 
      "CoxeterGroups`SqareComplexes`"}}, {"Documentation", 
    Language -> "English", LinkBase -> "CoxeterGroups", 
    Resources -> {"Guides/Automorphisms", "Guides/Coxeter system data", 
      "Guides/Group elements", "Guides/Manipulating group elements", 
      "Guides/Pre-defined Coxeter systems", "Guides/Special subgroups", 
      "Tutorials/Defining a new Coxeter system", 
      "Tutorials/Exporting and Importing group element data", 
      "Tutorials/Working with group elements", 
      "ReferencePages/Symbols/BilinearForm", "ReferencePages/Symbols/Braid", 
      "ReferencePages/Symbols/CoxeterAdjacencyMatrix", 
      "ReferencePages/Symbols/CoxeterComplexDimension", 
      "ReferencePages/Symbols/CoxeterDiagram", 
      "ReferencePages/Symbols/CoxeterElement", 
      "ReferencePages/Symbols/CoxeterGroupElements", 
      "ReferencePages/Symbols/CoxeterLength", 
      "ReferencePages/Symbols/CoxeterMultiply", 
      "ReferencePages/Symbols/CoxeterNumber", 
      "ReferencePages/Symbols/CoxeterReduce", 
      "ReferencePages/Symbols/DavisComplexDimension", 
      "ReferencePages/Symbols/DeleteRepeatedElements", 
      "ReferencePages/Symbols/E6", "ReferencePages/Symbols/E7", 
      "ReferencePages/Symbols/E8", "ReferencePages/Symbols/EE6", 
      "ReferencePages/Symbols/EE7", "ReferencePages/Symbols/EE8", 
      "ReferencePages/Symbols/ElementDirName", 
      "ReferencePages/Symbols/EnumeratedQ", 
      "ReferencePages/Symbols/EuclideanCGQ", 
      "ReferencePages/Symbols/EvenCGQ", 
      "ReferencePages/Symbols/ExportElementList", 
      "ReferencePages/Symbols/F4", "ReferencePages/Symbols/FE4", 
      "ReferencePages/Symbols/FindCoxeterReducedWord", 
      "ReferencePages/Symbols/FormSignature", 
      "ReferencePages/Symbols/FreeCG", "ReferencePages/Symbols/G2", 
      "ReferencePages/Symbols/GE2", "ReferencePages/Symbols/Generators", 
      "ReferencePages/Symbols/GroupName", "ReferencePages/Symbols/GroupSize", 
      "ReferencePages/Symbols/H3", "ReferencePages/Symbols/H4", 
      "ReferencePages/Symbols/HyperbolicCGQ", "ReferencePages/Symbols/I2", 
      "ReferencePages/Symbols/IrreducibleCGQ", 
      "ReferencePages/Symbols/IrreducibleFactor", 
      "ReferencePages/Symbols/IrreducibleFactors", 
      "ReferencePages/Symbols/IrreducibleSpecialSubgroups", 
      "ReferencePages/Symbols/LengthEnumerated", 
      "ReferencePages/Symbols/LinearWordProblem", 
      "ReferencePages/Symbols/LongestElement", 
      "ReferencePages/Symbols/MaxLength", 
      "ReferencePages/Symbols/PresentationAdjacencyMatrix", 
      "ReferencePages/Symbols/PresentationDiagram", 
      "ReferencePages/Symbols/RABipartiteG", "ReferencePages/Symbols/RACGQ", 
      "ReferencePages/Symbols/RACGroup", "ReferencePages/Symbols/RAPolygonG", 
      "ReferencePages/Symbols/SmoothEnumeratedQ", 
      "ReferencePages/Symbols/SpecialSubgroup", 
      "ReferencePages/Symbols/SpecialSubgroups", 
      "ReferencePages/Symbols/SphericalCGQ", 
      "ReferencePages/Symbols/SphericalSubgroups", 
      "ReferencePages/Symbols/TitsM1", "ReferencePages/Symbols/TitsM2", 
      "ReferencePages/Symbols/TitsRepresentation", 
      "ReferencePages/Symbols/TitsWordProblem", 
      "ReferencePages/Symbols/TriangleCG", "ReferencePages/Symbols/TypeAE", 
      "ReferencePages/Symbols/TypeA", "ReferencePages/Symbols/TypeBE", 
      "ReferencePages/Symbols/TypeB", "ReferencePages/Symbols/TypeCE", 
      "ReferencePages/Symbols/TypeC", "ReferencePages/Symbols/TypeDE", 
      "ReferencePages/Symbols/TypeD", 
      "ReferencePages/Symbols/ValidCoxeterMatrixQ"}}}]
