(* Created with the Wolfram Language : www.wolfram.com *)
Paclet[Name -> "CoxeterGroups", Version -> "0.0.1", 
 MathematicaVersion -> "8+", Extensions -> 
  {{"Kernel", "Context" -> {"CoxeterGroups`BasicCoxeterFunctions`"}}, 
   {"Documentation", Language -> "English", LinkBase -> "CoxeterGroups", 
    Resources -> {"Guides/Automorphisms", "Guides/Coxeter system data", 
      "Guides/Manipulating group elements", 
      "Guides/Pre-defined Coxeter systems", "Guides/Special subgroups", 
      "Tutorials/Defining a new Coxeter system", 
      "ReferencePages/Symbols/BilinearForm", 
      "ReferencePages/Symbols/ConnectedComponentUnionQ", 
      "ReferencePages/Symbols/ConvertFromSpecialSubgroup", 
      "ReferencePages/Symbols/ConvertToSpecialSubgroup", 
      "ReferencePages/Symbols/DiagramNeighbours", 
      "ReferencePages/Symbols/E6", "ReferencePages/Symbols/E7", 
      "ReferencePages/Symbols/E8", "ReferencePages/Symbols/EE6", 
      "ReferencePages/Symbols/EE7", "ReferencePages/Symbols/EE8", 
      "ReferencePages/Symbols/EuclideanCGQ", 
      "ReferencePages/Symbols/EvenCGQ", "ReferencePages/Symbols/F4", 
      "ReferencePages/Symbols/FE4", "ReferencePages/Symbols/FormSignature", 
      "ReferencePages/Symbols/FreeCG", "ReferencePages/Symbols/G2", 
      "ReferencePages/Symbols/GE2", "ReferencePages/Symbols/Generators", 
      "ReferencePages/Symbols/GroupName", "ReferencePages/Symbols/H3", 
      "ReferencePages/Symbols/H4", "ReferencePages/Symbols/HyperbolicCGQ", 
      "ReferencePages/Symbols/I2", "ReferencePages/Symbols/IrreducibleCGQ", 
      "ReferencePages/Symbols/IrreducibleFactorComplement", 
      "ReferencePages/Symbols/IrreducibleFactor", 
      "ReferencePages/Symbols/IrreducibleFactors", 
      "ReferencePages/Symbols/IrreducibleSpecialSubgroups", 
      "ReferencePages/Symbols/RABipartiteG", "ReferencePages/Symbols/RACGQ", 
      "ReferencePages/Symbols/RACGroup", "ReferencePages/Symbols/RAPolygonG", 
      "ReferencePages/Symbols/SpecialSubgroup", 
      "ReferencePages/Symbols/SphericalCGQ", 
      "ReferencePages/Symbols/SymmetricEntry", 
      "ReferencePages/Symbols/TriangleCG", "ReferencePages/Symbols/TypeAE", 
      "ReferencePages/Symbols/TypeA", "ReferencePages/Symbols/TypeBE", 
      "ReferencePages/Symbols/TypeB", "ReferencePages/Symbols/TypeCE", 
      "ReferencePages/Symbols/TypeC", "ReferencePages/Symbols/TypeDE", 
      "ReferencePages/Symbols/TypeD"}}}]
